#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# 1. Build the contracts
# 2. Stage build output
# 2. Lint and stage style improvements
yarn workspace @x-everest/protocol build && git add packages/protocol && npx lint-staged
